NHSLeadership/nightingale-wp

inc/walker-menu.php

Fix error when subnav lacks a panel.
Now, when a subnav has a panel, it looks like this:
And without a panel, it looks like this:

[refs #00089] Allow for subnavs without panels

---

style.scss
style/settings.scss

Set $asset-path variable to node_modules folder within theme folder.

[refs #00092] Define assets path

---

style.scss
style/quotes.scss

Apply Nightingale styling to blockquotes.
I've done this by extending the c-quote class.
Please note that, if the alternative quote style is needed (white on purple), the admin should add a class of 'c-quote--rev' to the blockquote element.

[refs #00024] Style quotes

---

style/navigation.scss

Title saying "Other Posts" isn't needed, so hide it (but keep it for screen readers).

[refs #00105] Hide pagination title

---

.gitignore
Dockerfile

This add a dockerfile to build in Bamboo

Docker build

---

page-sitemap.php

Page template for displaying sitemap.

[refs #00134] Add sitemap template

---

single.php
template-parts/acf-flex.php
template-parts/acf-link-block.php
template-parts/acf-links.php
template-parts/content-excerpt.php
template-parts/content-secondary.php
template-parts/content-title.php
template-parts/content.php

Modified the post template to allow primary and secondary content using Advanced Custom Fields. Secondary content includes a link block.

Tkt 00133 - add ACF to post template

---

front-page.php
inc/template-tags.php
inc/widgets.php
template-parts/content-excerpt.php
template-parts/front-page-secondary.php

Displays 2 latest posts in sidebar as shown below:

Tkt 00129 - secondary content area on front page

---

template-parts/acf-links.php

Don't treat home page link headers and different to other headers.

[refs #00127] Remove homepage link class

---

inc/breadcrumbs.php
search.php
template-parts/content-search.php

Display search results with count at the top as shown below:

[refs #00116] search results page

---

template-parts/content.php

Display featured images listing pages where full posts are shown.

[refs #00160] Add featured image to post listings

---

archive.php

Use nightingale pagination on archive pages.

[refs #00162] Archive page pagination

---

inc/template-tags.php
template-parts/content-excerpt.php
template-parts/content-title.php
template-parts/content.php

The Read More link was being displayed at the bottom of full posts so I got rid of it.

[refs #00168] Show Read More link on excerpts only

---

comments.php
front-page.php
page.php
single.php

Allow admins to enable/disable comments and pingbacks.
Tested with all four possibilities of comments/pingbacks enabled/disabled.

[refs #00170] Honour comment/pingback settings

---

template-parts/acf-button.php

Allow for button_url being an array.

[refs #00191] Fix button links

---

template-parts/content-tabs.php

Add icons to tabs on mobile using a set list of icons as agreed with M&E.

[refs #00102] Mobile tab icons

---

functions.php
inc/gravity-view.php

Fix problem with Gravity View import entries plugin not triggering Gravity Flow form submission workflows correctly.

[refs #DI-88] Fix GF import entries error

---

Dockerfile

Add minified CSS build to Dockerfile.

[refs #DI-157] Minify CSS

---

wp-html-mail/template.html

Email template for WP HTML Mail plugin to use Nightingale styling.
A test email looks like this:

[refs #DI-131] Email template

---

inc/gravity-flow.php

Remove Gravity Flow code snippet as it didn't solve the problem it was intended to.

Refs [#DI-1098] Remove GF code snippet

---

composer.json

Nightingale theme composer file
